#[derive(Clone, Copy)]
pub struct TypeTheme {
    pub card_border: &'static str,
    pub card_bg_start: &'static str,
    pub card_bg_end: &'static str,
    pub tag_bg_start: &'static str,
    pub tag_bg_end: &'static str,
    pub tag_shadow: &'static str,
}

const DEFAULT_THEME: TypeTheme = TypeTheme {
    card_border: "#2a75bb",
    card_bg_start: "#f4f4f4",
    card_bg_end: "#e8e8e8",
    tag_bg_start: "#7AC74C",
    tag_bg_end: "#5a9c3c",
    tag_shadow: "0 4px 12px rgba(122, 199, 76, 0.5)",
};

pub fn theme_for(type_name: &str) -> TypeTheme {
    match type_name {
        "bug" => TypeTheme {
            card_border: "#A6B91A",
            card_bg_start: "#f5f8d2",
            card_bg_end: "#dfe68f",
            tag_bg_start: "#A6B91A",
            tag_bg_end: "#8a9c14",
            tag_shadow: "0 4px 12px rgba(166, 185, 26, 0.5)",
        },
        "dark" => TypeTheme {
            card_border: "#705746",
            card_bg_start: "#e4d8d1",
            card_bg_end: "#cdbfb7",
            tag_bg_start: "#705746",
            tag_bg_end: "#564232",
            tag_shadow: "0 4px 12px rgba(112, 87, 70, 0.5)",
        },
        "dragon" => TypeTheme {
            card_border: "#6F35FC",
            card_bg_start: "#e4dbff",
            card_bg_end: "#c7b2ff",
            tag_bg_start: "#6F35FC",
            tag_bg_end: "#4f1ad9",
            tag_shadow: "0 4px 12px rgba(111, 53, 252, 0.5)",
        },
        "electric" => TypeTheme {
            card_border: "#F7D02C",
            card_bg_start: "#fff7c6",
            card_bg_end: "#ffe680",
            tag_bg_start: "#F7D02C",
            tag_bg_end: "#d4af1f",
            tag_shadow: "0 4px 12px rgba(247, 208, 44, 0.5)",
        },
        "fairy" => TypeTheme {
            card_border: "#D685AD",
            card_bg_start: "#ffe3f0",
            card_bg_end: "#f6bfd8",
            tag_bg_start: "#D685AD",
            tag_bg_end: "#b9648c",
            tag_shadow: "0 4px 12px rgba(214, 133, 173, 0.5)",
        },
        "fighting" => TypeTheme {
            card_border: "#C22E28",
            card_bg_start: "#f7d6d4",
            card_bg_end: "#e9a29b",
            tag_bg_start: "#C22E28",
            tag_bg_end: "#9b231f",
            tag_shadow: "0 4px 12px rgba(194, 46, 40, 0.5)",
        },
        "fire" => TypeTheme {
            card_border: "#EE8130",
            card_bg_start: "#fff3e0",
            card_bg_end: "#ffe0b2",
            tag_bg_start: "#EE8130",
            tag_bg_end: "#c86420",
            tag_shadow: "0 4px 12px rgba(238, 129, 48, 0.5)",
        },
        "flying" => TypeTheme {
            card_border: "#A98FF3",
            card_bg_start: "#f1e9ff",
            card_bg_end: "#d5c8fa",
            tag_bg_start: "#A98FF3",
            tag_bg_end: "#8970d8",
            tag_shadow: "0 4px 12px rgba(169, 143, 243, 0.5)",
        },
        "ghost" => TypeTheme {
            card_border: "#735797",
            card_bg_start: "#e5dcf3",
            card_bg_end: "#c9b8dd",
            tag_bg_start: "#735797",
            tag_bg_end: "#57406f",
            tag_shadow: "0 4px 12px rgba(115, 87, 151, 0.5)",
        },
        "grass" => TypeTheme {
            card_border: "#7AC74C",
            card_bg_start: "#e8f5e9",
            card_bg_end: "#c8e6c9",
            tag_bg_start: "#7AC74C",
            tag_bg_end: "#5a9c3c",
            tag_shadow: "0 4px 12px rgba(122, 199, 76, 0.5)",
        },
        "ground" => TypeTheme {
            card_border: "#E2BF65",
            card_bg_start: "#fdf0d1",
            card_bg_end: "#eed2a4",
            tag_bg_start: "#E2BF65",
            tag_bg_end: "#c79f47",
            tag_shadow: "0 4px 12px rgba(226, 191, 101, 0.5)",
        },
        "ice" => TypeTheme {
            card_border: "#96D9D6",
            card_bg_start: "#e7fafa",
            card_bg_end: "#c8ebea",
            tag_bg_start: "#96D9D6",
            tag_bg_end: "#75bebb",
            tag_shadow: "0 4px 12px rgba(150, 217, 214, 0.5)",
        },
        "normal" => TypeTheme {
            card_border: "#A8A77A",
            card_bg_start: "#f5f5dc",
            card_bg_end: "#e2e2c4",
            tag_bg_start: "#A8A77A",
            tag_bg_end: "#8e8d61",
            tag_shadow: "0 4px 12px rgba(168, 167, 122, 0.5)",
        },
        "poison" => TypeTheme {
            card_border: "#A33EA1",
            card_bg_start: "#f4e1f3",
            card_bg_end: "#deb3db",
            tag_bg_start: "#A33EA1",
            tag_bg_end: "#832e81",
            tag_shadow: "0 4px 12px rgba(163, 62, 161, 0.5)",
        },
        "psychic" => TypeTheme {
            card_border: "#F95587",
            card_bg_start: "#ffe0eb",
            card_bg_end: "#ffb3cc",
            tag_bg_start: "#F95587",
            tag_bg_end: "#d83a69",
            tag_shadow: "0 4px 12px rgba(249, 85, 135, 0.5)",
        },
        "rock" => TypeTheme {
            card_border: "#B6A136",
            card_bg_start: "#f1e7c2",
            card_bg_end: "#ddc67c",
            tag_bg_start: "#B6A136",
            tag_bg_end: "#9a832d",
            tag_shadow: "0 4px 12px rgba(182, 161, 54, 0.5)",
        },
        "steel" => TypeTheme {
            card_border: "#B7B7CE",
            card_bg_start: "#eef0fb",
            card_bg_end: "#d0d5e9",
            tag_bg_start: "#B7B7CE",
            tag_bg_end: "#9494b0",
            tag_shadow: "0 4px 12px rgba(183, 183, 206, 0.5)",
        },
        "water" => TypeTheme {
            card_border: "#6390F0",
            card_bg_start: "#e0ebff",
            card_bg_end: "#bad0ff",
            tag_bg_start: "#6390F0",
            tag_bg_end: "#4d74c7",
            tag_shadow: "0 4px 12px rgba(99, 144, 240, 0.5)",
        },
        _ => DEFAULT_THEME,
    }
}
